content_search_max_file_size = "10MB"
enable_kitty_keyboard = false
icon_theme = "nerdfont"
imports = ["verbs.hjson", {file = "skins/dark-blue.hjson", luma = ["dark", "unknown"]}, {file = "skins/white.hjson", luma = "light"}, "skins/catppuccin-mocha.hjson"]
lines_after_match_in_preview = 1
lines_before_match_in_preview = 1
modal = false
show_selection_mark = true
syntax_theme = "MochaDark"
verbs = []

[skin]

[special_paths]
[special_paths."/media"]
list = "never"
sum = "never"

[special_paths.trav]
list = "always"
show = "always"
sum = "never"

[special_paths."~/.config"]
show = "always"
